ycu-engine/ycu-engine.github.io

- .github/workflows/gh-pages.yml
- .github/workflows/pr-check.yml
> github actionsにキャッシュ戦略を追加

- src/data/member.ts
> Kotaro Takamoriを追加しました

- src/data/member.ts
> 小檜山祥央追加しました

- src/data/activity_log/20210128_general_1.mdx
- src/data/member.ts
> 20210128オリエンの活動記録

- src/data/member.ts
- src/gatsby/node.ts
> ゴブリンが日本語だと困るので修正

- src/data/member.ts
> githubアカウント載せました

- src/data/member.ts
> <自分の名前>を追加しました。

- src/data/member.ts
> 名前の追加を行いました。

- src/data/member.ts
> <KentaroMorota>を追加しました

- src/data/member.ts
> <TsuyoshiMatsumaru>を追加しました。

- src/data/activity_log/20210129_beginner.mdx
- src/data/member.ts
- src/data/team.ts
> 2021年1月29日 1年生向けにオリエンテーションを実施

- .github/workflows/gh-pages.yml
- .github/workflows/pr-check.yml
> ワークフローでpaths-ignoreを設定

- src/data/activity_log/20210129_data_analitics.mdx
> 2021年1月29日 Kaggle会

- graphql-types.ts
- src/data/activity_log/20210208_beginner.mdx
> 2021年2月8日 ビギナー会活動報告

- src/data/activity_log/20210208_beginner.mdx
- src/data/member.ts
> <RenAgo>を追加しました

- src/data/activity_log/20210210_app-dev.mdx
- src/data/team.ts
> feat: src/data/activity_log/20210210_app-dev.mdx

- src/data/activity_log/20210212_beginner.mdx
> 2021年2月12日 ビギナーチームの活動報告

- eslint/mdx/rule/mdx-components.js
- src/data/activity_log/20210112_general.mdx
- src/data/activity_log/20210129_web.mdx
- src/data/activity_log/20210210_app-dev.mdx
- src/data/member.ts
- src/data/team.ts
> change web team to webdev

- src/data/activity_log/20210301_beginner.mdx
> 2021年3月1日 ビギナー活動報告

- .husky/post-merge
> マージ後に自動で依存関係をインストールするように変更

- graphql-types.ts
- package.json
- schema.json
- src/components/atoms/image-wrapper.tsx
- src/components/atoms/section-content.tsx
- src/components/atoms/section-title.tsx
- src/components/atoms/team-icon.tsx
- src/components/molecules/section.tsx
- src/data/activity_log/20210129_beginner.mdx
- src/data/activity_log/20210129_web.mdx
- src/data/activity_log/20210208_beginner.mdx
- src/data/activity_log/20210210_app-dev.mdx
- src/data/activity_log/20210212_beginner.mdx
- src/data/activity_log/20210219_beginner.mdx
- src/data/activity_log/20210301_beginner.mdx
- src/data/member.ts
- src/gatsby/node/create-pages.ts
- src/gatsby/node/create-resolvers.ts
- src/gatsby/node/create-schema-customization.ts
- src/lib/filter.ts
- src/templates/member.tsx
- src/templates/team.tsx
- yarn.lock
> チームページとメンバーページの修正

- src/data/team.ts
> ビギナーチームが一番下になるように変更

- gatsby-config.js
- graphql-types.ts
- schema.json
> gtagの設定を修正

- src/data/activity_log/20210305_data_analitics.mdx
> 2021年3月5日 データ分析チーム活動報告

- gatsby-config.js
- graphql-types.ts
- package.json
- schema.json
- src/components/organisms/SEO.tsx
- yarn.lock
> robots.txt

- src/data/events/2021-pc-consultation-meeting.mdx
> update google form link

- src/data/events/2021-pc-consultation-meeting.mdx
> update event form

- graphql-types.ts
- schema.json
- src/components/organisms/SEO.tsx
> fix og:image

- graphql-types.ts
- schema.json
- src/components/organisms/Header.tsx
- src/data/events/2021-pc-consultation-meeting.mdx
> イベントのデータを修正

- src/data/activity_log/20210313_data_analitics.mdx
> 20210313 data analytics2

- src/data/activity_log/20210313_data_analitics.mdx
> 20210313 data

- graphql-types.ts
- schema.json
- src/data/activity_log/20210315_beginner1.mdx
- src/data/activity_log/20210315_beginner2.mdx
> 2021年3月15日ビギナー活動報告

- src/data/activity_log/20210320_data_analitics.mdx
> 2021年3月20日 データ分析チーム活動報告

- src/data/activity_log/20210327_beginner.mdx
> 2021年3月27日 ビギナーチーム活動報告

- src/data/activity_log/20210327_beginner.mdx
- src/data/activity_log/20210409_beginner.mdx
> 2021年4月9日 ビギナーチーム活動報告

- src/data/activity_log/20210411_data_analitics.mdx
> 2021年4月11日 分析チーム活動報告

- src/data/activity_log/20210414_app-dev.mdx
> 2021年4月14日 アプリ開発チーム活動報告

- src/data/activity_log/20210425_beginner.mdx
- src/data/activity_log/20210425_data_analitics.mdx
> 2021年4月25日 ビギナー・分析チームの活動報告

- src/data/activity_log/20210508_data_analitics.mdx
> 2021年5月8日 分析チームの活動報告

- src/data/activity_log/20210523_data_analitics.mdx
> 活動報告 2021年5月23日 データ分析チーム

- src/data/activity_log/20210618_begginer.mdx
- src/data/portfolio.ts
> 20210618 biggner 週一ミーティング

- src/data/activity_log/20210711_begginer.mdx
- src/data/member.ts
> 活動報告 2021年7月11日 ビギナー
